using AtomicAssetsApiClient.Accounts;
using AtomicAssetsApiClient.Assets;
using AtomicAssetsApiClient.Burns;
using AtomicAssetsApiClient.Collections;
using AtomicAssetsApiClient.Config;
using AtomicAssetsApiClient.Offers;
using AtomicAssetsApiClient.Schemas;
using AtomicAssetsApiClient.Templates;
using AtomicAssetsApiClient.Transfers;

namespace AtomicAssetsApiClient
{
    public class AtomicAssetsApiFactory
    {
        private readonly string _baseUrl;
        private const string AtomicAssetsIO = "https://wax.api.atomicassets.io/atomicassets/v1";
        private const string EOSAmsterdam = "https://wax-aa.eu.eosamsterdam.net/atomicassets/v1";
        private const string EOSAuthority = "https://aa-api-wax.eosauthority.com/atomicassets/v1";
        private const string testnet3DK = "https://testatomic.3dkrender.com/atomicassets/v1";
        private const string testnetNefty = "https://aa-testnet-public.neftyblocks.com/atomicassets/v1";

        private AtomicAssetsApiFactory(string baseUrl) => _baseUrl = baseUrl;

        /* It's a static property that returns a new instance of the AtomicAssetsApiFactory class. */
        public static AtomicAssetsApiFactory MainNet1 => new AtomicAssetsApiFactory(AtomicAssetsIO);
        public static AtomicAssetsApiFactory MainNet2 => new AtomicAssetsApiFactory(EOSAmsterdam);
        public static AtomicAssetsApiFactory MainNet3 => new AtomicAssetsApiFactory(EOSAuthority);
        public static AtomicAssetsApiFactory TestNet1 => new AtomicAssetsApiFactory(testnet3DK);
        public static AtomicAssetsApiFactory TestNet2 => new AtomicAssetsApiFactory(testnetNefty);
 
        /// <summary>
        /// The AccountsApi function returns a new AccountsApi object, which is a class that inherits
        /// from the AccountsApiBase class
        /// </summary>
        /// <param name="_baseUrl">The base URL for the API.</param>
        public AccountsApi AccountsApi => new AccountsApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the AssetsApi class.
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public AssetsApi AssetsApi => new AssetsApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new BurnsApi object.
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public BurnsApi BurnsApi => new BurnsApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the CollectionsApi class.
        /// </summary>
        /// <param name="_baseUrl">The base URL for the API.</param>
        public CollectionsApi CollectionsApi => new CollectionsApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// The ConfigApi function returns a new instance of the ConfigApi class, which is a class that
        /// is generated by the Swagger Codegen tool
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public ConfigApi ConfigApi => new ConfigApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the OffersApi class.
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public OffersApi OffersApi => new OffersApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the SchemasApi class.
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public SchemasApi SchemasApi => new SchemasApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the TemplatesApi class, passing in the baseUrl variable
        /// </summary>
        /// <param name="_baseUrl">The base URL of the API.</param>
        public TemplatesApi TemplatesApi => new TemplatesApi(_baseUrl, new HttpHandler());

        /// <summary>
        /// It creates a new instance of the TransfersApi class.
        /// </summary>
        /// <param name="_baseUrl">The base URL for the API.</param>
        public TransfersApi TransfersApi => new TransfersApi(_baseUrl, new HttpHandler());
    }
}
